apiVersion: apps/v1
kind: Deployment
metadata:
  name: onekey-sample-web-app
  namespace: onekey-web
  labels:
    name: onekey-sample-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: onekey-sample-web-app
  template:
    metadata:
      labels:
        app: onekey-sample-web-app
    spec:
      containers:
        - name: onekey-sample-web-app
          image: onekeyprodregistry.azurecr.io/onekey-sdk-web-lib:b26d70e
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  labels:
  name:  onekey-sample-web-app
  namespace: onekey-web
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 5000
  selector:
    app: onekey-sample-web-app
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: onekey-sample-web-app
  namespace: onekey-web
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    kubernetes.io/ingress.class: onekey-web
spec:
  rules:
    - host: frontdoor-prod-westeu-onekey.azurefd.net 
    - http:
        paths:
        - backend:
            serviceName: onekey-sample-web-app
            servicePort: 80
          path: "/sample"
          pathType: Prefix
