
pool:
  vmImage: windows-latest

variables:
  storage_key: $(storagekey)
  storage_name: $(storagename)


steps:

 - task: AzureCLI@2
   inputs:
     azureSubscription: 'Onekey'
     scriptType: 'ps'
     scriptLocation: 'inlineScript'
     inlineScript: 'az storage blob upload-batch --account-name $(storage_name) --account-key $(storage_key) --destination $web --destination-path hcl-sdk-api --source $(Build.ArtifactStagingDirectory)/hcl-sdk-api'
     
 - task: AzureCLI@2
   inputs:
     azureSubscription: 'Onekey'
     scriptType: 'ps'
     scriptLocation: 'inlineScript'
     inlineScript: 'az storage blob upload-batch --account-name $(storage_name) --account-key $(storage_key) --destination $web --destination-path hcl-sdk-web-ui --source $(Build.ArtifactStagingDirectory)/hcl-sdk-web-ui'
  