trigger:
- master

pool:
  vmImage: windows-latest

steps:

  - task: AzureFileCopy@4
    inputs:
      SourcePath: '$(Build.ArtifactStagingDirectory)/hcl-sdk-web-ui-$(Build.BuildId).zip'
      azureSubscription: 'Onekey'
      Destination: 'AzureBlob'
      ContainerName: 'onekeydataprodwesteu'
      BlobPrefix: '$web/hcl-sdk-web-ui'
    
  - task: AzureFileCopy@4
    inputs:
      SourcePath: '$(Build.ArtifactStagingDirectory)/hcl-sdk-api-ui-$(Build.BuildId).zip'
      azureSubscription: 'Onekey'
      Destination: 'AzureBlob'
      ContainerName: 'onekeydataprodwesteu'
      BlobPrefix: '$web/hcl-sdk-web-ui'
