
pool:
  vmImage: windows-latest

variables:
  storage_key: $(storagekey)
  storage_name: $(storagename)


steps:
- checkout: self
  path: s/onekey-sdk-web-lib

- task: YarnInstaller@3
  inputs:
    versionSpec: '1.x'

- task: Yarn@3
  displayName: 'Install dependencies'
  inputs:
    arguments: 'install'

- task: Yarn@3
  displayName: 'Build Web UI'
  inputs:
    arguments: 'build-web'
    
- task: Yarn@3
  displayName: 'Build API'
  inputs:
    arguments: 'build-api'


- task: AzureCLI@2
  inputs:
    azureSubscription: 'Onekey'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: "az storage blob upload-batch -d '$web' --destination-path 'hcl-sdk-web-ui' --account-name ${env:STORAGENAME} --account-key ${env:STORAGEKEY} -s ./"
    workingDirectory: $(Build.SourcesDirectory)/onekey-sdk-web-lib/packages/hcl-sdk-web-ui/dist

- task: AzureCLI@2
  inputs:
    azureSubscription: 'Onekey'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: "az storage blob upload-batch -d '$web' --destination-path 'hcl-sdk-api' --account-name ${env:STORAGENAME} --account-key ${env:STORAGEKEY} -s ./"
    workingDirectory: $(Build.SourcesDirectory)/onekey-sdk-web-lib/packages/hcl-sdk-api/dist
 
