
pool:
  vmImage: windows-latest

steps:

 - task: AzureCLI@2
   inputs:
     azureSubscription: 'Onekey'
     scriptType: 'ps'
     scriptLocation: 'inlineScript'
     inlineScript: 'az storage blob upload-batch — account-name $(storagename) account-key $(storagekey) — destination ‘$web’ — source $(Build.ArtifactStagingDirectory)\hcl-sdk-web-ui-$(Build.BuildId).zip'
