
pool:
  vmImage: windows-latest

variables:
  storage_account: $(storagename)
  storage_key: $(storagekey)

steps:

 - task: AzureCLI@2
   inputs:
     azureSubscription: 'Onekey'
     scriptType: 'ps'
     scriptLocation: 'inlineScript'
     inlineScript: 'az storage blob upload-batch  --account-name $(storage_account) --account-key $(storage_key) —d $web --destination-path hcl-sdk-api —s $(Build.ArtifactStagingDirectory)/hcl-sdk-api'
     
 - task: AzureCLI@2
   inputs:
     azureSubscription: 'Onekey'
     scriptType: 'ps'
     scriptLocation: 'inlineScript'
     inlineScript: 'az storage blob upload-batch  --account-name $(storage_account) --account-key $(storage_key) —d $web --destination-path hcl-sdk-web-ui —s $(Build.ArtifactStagingDirectory)/hcl-sdk-web-ui'
  