name: $(Build.SourceBranch)

trigger:
  - development

parameters:
  - name: azcrconnectionparam
    displayName: Docker connection
    type: string
    default: onekeyprodregistry.azurecr.io-onekey-sdk-web-lib
  - name: azcrhostparam
    displayName: Docker host
    type: string
    default: onekeyprodregistry.azurecr.io-onekey-sdk-web-lib
  - name: azkubeserviceparam
    displayName: Kubernetes Service Connection
    type: string
    default: argo.aks-dev-eastus-onekey-sdk-web-lib
  - name: azkubeserviceWestEUparam
    displayName: Kubernetes Service Connection westEU
    type: string
    default: aks-prod-westeu-onekey-k8s-onekey-sdk-web-lib

pool:
  vmImage: 'ubuntu-latest'

variables:
  azcrconnection: ${{ parameters.azcrconnectionparam }}
  azkubeservice: ${{ parameters.azkubeserviceparam }}
  azWestEUkubeservice: ${{ parameters.azkubeserviceWestEUparam }}
  azcrimage: $(azcrhost)/$(Build.Repository.Name)

steps:
  - checkout: self
    path: s/onekey-sdk-web-lib

  - script: |
      echo '##vso[task.setvariable variable=buildSHA]'$(git rev-parse --short HEAD)''
      echo 'buildSHA set to '$(buildSHA)''
    displayName: Get build git SHA
    workingDirectory: $(pipeline.workspace)/s/onekey-sdk-web-lib

  - task: Docker@2
    displayName: Docker login
    inputs:
      command: login
      containerRegistry: $(azcrconnection)

  - task: Docker@2
    displayName: Build image
    inputs:
      containerRegistry: $(azcrconnection)
      repository: $(Build.Repository.Name)
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
      tags: $(buildSHA)

  - task: Docker@2
    displayName: Build latest
    inputs:
      containerRegistry: $(azcrconnection)
      repository: $(Build.Repository.Name)
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
      tags: latest
