# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: windows-latest

steps:

- checkout: self
  path: s/onekey-sdk-web-lib
    
- task: YarnInstaller@3
  inputs:
    versionSpec: '1.x'

- task: Yarn@3
  displayName: 'Install dependencies'
  inputs:
    arguments: 'install'

- task: Yarn@3
  displayName: 'Build Web UI'
  inputs:
    arguments: 'build-web'
    
- task: Yarn@3
  displayName: 'Build API'
  inputs:
    arguments: 'build-api'

- task: AzureFileCopy@4
  inputs:
    SourcePath: '$(Build.SourcesDirectory)/packages/hcl-sdk-web-ui/dist'
    azureSubscription: 'Onekey'
    Destination: 'AzureBlob'
    ContainerName: 'onekeydataprodwesteu'
    BlobPrefix: '$web/hcl-sdk-web-ui'
    