
pool:
  vmImage: windows-latest

variables:
  storage_key: $(storagekey)
  storage_name: $(storagename)


steps:
- checkout: self
  path: s/onekey-sdk-web-lib

- task: YarnInstaller@3
  inputs:
    versionSpec: '1.x'

- task: Yarn@3
  displayName: 'Install dependencies'
  inputs:
    arguments: 'install'

- task: Yarn@3
  displayName: 'Build Web UI'
  inputs:
    arguments: 'build-web'
    
- task: Yarn@3
  displayName: 'Build API'
  inputs:
    arguments: 'build-api'

- task: AzureFileCopy@4
  inputs:
    sourcePath: onekey-sdk-web-lib/packages/hcl-sdk-web-ui/dist
    azureSubscription: 'Onekey'
    destination: 'onekeySDK'
    storage: $(storagename)
    containerName: $web
    blobPrefix: 'hcl-sdk-web-ui'

- task: AzureFileCopy@4
  inputs:
    sourcePath: onekey-sdk-web-lib/packages/hcl-sdk-api/dist
    azureSubscription: 'Onekey'
    destination: 'onekeySDK'
    storage: $(storagename)
    containerName: $web
    blobPrefix: 'hcl-sdk-api'
