name: $(Build.SourceBranch)

trigger:
  - release/1.0.0

parameters:
  - name: azcrconnectionparam
    displayName: Docker connection
    type: string
    default: onekeyprodregistry.azurecr.io-onekey-sdk-web-lib
  - name: azcrhostparam
    displayName: Docker host
    type: string
    default: onekeyprodregistry.azurecr.io-onekey-sdk-web-lib
  - name: azkubeserviceparam
    displayName: Kubernetes Service Connection
    type: string
    default: argo.aks-dev-eastus-onekey-sdk-web-lib
  - name: azkubeserviceWestEUparam
    displayName: Kubernetes Service Connection westEU
    type: string
    default: aks-prod-westeu-onekey-k8s-onekey-sdk-web-lib

pool:
  vmImage: 'ubuntu-latest'

variables:
  azcrconnection: ${{ parameters.azcrconnectionparam }}
  azkubeservice: ${{ parameters.azkubeserviceparam }}
  azWestEUkubeservice: ${{ parameters.azkubeserviceWestEUparam }}
  azcrimage: $(azcrhost)/$(Build.Repository.Name)
  cdnUrl: $(cdn.url)

steps:
  - checkout: self
    path: s/onekey-sdk-web-lib

  - script: |
      echo '##vso[task.setvariable variable=buildSHA]'$(git rev-parse --short HEAD)''
      echo 'buildSHA set to '$(buildSHA)''
    displayName: Get build git SHA
    workingDirectory: $(pipeline.workspace)/s/onekey-sdk-web-lib

  - task: RegExMatchReplace@2
    inputs:
      PathToFile: 'examples/web/cdn/index.html'
      RegEx: '<script src="\.'
      ValueToReplace: "<script src=\"$(cdnUrl)"
      Global: true

  - task: RegExMatchReplace@2
    inputs:
      PathToFile: 'examples/web/cdn/search.html'
      RegEx: '<script src="\.'
      ValueToReplace: "<script src=\"$(cdnUrl)"
      Global: true

  - task: Docker@2
    displayName: Docker login
    inputs:
      command: login
      containerRegistry: $(azcrconnection)

  - task: Docker@2
    displayName: Build image
    inputs:
      containerRegistry: $(azcrconnection)
      repository: $(Build.Repository.Name)
      command: 'buildAndPush'
      Dockerfile: 'devops/Dockerfile.app'
      tags: $(buildSHA)
      buildContext: '.'

  - task: Docker@2
    displayName: Build latest
    inputs:
      containerRegistry: $(azcrconnection)
      repository: $(Build.Repository.Name)
      command: 'buildAndPush'
      Dockerfile: 'devops/Dockerfile.app'
      buildContext: '.'
      tags: latest

<<<<<<< HEAD
  - task: CopyFiles@2
    inputs:
      contents: "examples/web/cdn/*"
      targetFolder: "$(build.artifactStagingDirectory)"
      overWrite: true

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: "$(build.artifactStagingDirectory)"
      artifactName: "sample-app"
      publishLocation: "Container"
=======
>>>>>>> 8cff8552bf123a0188275bedcb2f16822a44dbd3
